### ISSUE TITLE
programs don't work

### ISSUE THREAD

**Issue by joseph-zou** [Heatwave/The-C-Programming-Language-2nd-Edition#1]
for some reason the codes in this book give me no output only allows me to input.

PLEASE HELP!!!

#include <stdio.h>

/* count characters in input; 1st version */
main()
{
	long nc;

	nc = 0;
	while (getchar() != EOF)
		++nc;
	printf("%ld\n", nc);
}

**Comment by Heatwave** [comment]
@Joey2441-spec What's your operating system, compiler? And how do you run this code?

**Comment by joseph-zou** [comment]
My program wouldn't quit so it kept asking for input. I just pressed ctrl D to end it and it worked. Thanks for replying back. 👍
